"""add raw content and llm content

Revision ID: 55efcf5313e4
Revises:
Create Date: 2024-11-17 01:06:42.052593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55efcf5313e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('llm_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_column('llm_content')
        batch_op.drop_column('raw_content')

    # ### end Alembic commands ###
